### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by azukiboy**
## Overview
1. fix all text typo with spell checker(mainly *.md)
2. CI may be considered in the next step ref:codespell-project/codespell

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by azukiboy** [comment]
Most of it is as expected, some words may be corrected incorrectly,  like crate->create. WIP

**Review by rootulp — APPROVED** [review]

**Comment by rootulp** [comment]
Thanks for the contribution @azukiboy !

**Review by staheri14 — APPROVED** [review]
Thanks!

**Comment by rootulp** [comment]
After merging in main, it looks like this PR is a no-op because no files changed.

**Pull request closed without merging**
