### PR TITLE
chore: 10 second timeout for `make test-short`

### LINKED ISSUE #1897: Reduce running time of `make test-short`
## Problem

```shell
make test-short
```

takes a while to run

## Proposal

Skip tests that take > 10 seconds to run:

```shell
ok  	github.com/celestiaorg/celestia-app/test/txsim	151.956s
...
ok  	github.com/celestiaorg/celestia-app/x/mint/client/testutil	16.795s
```

### PR DESCRIPTION
**Pull request by krishnaduttPanchagnula**
## Overview
Currently `make test-short` is taking quite a while to run even after the -short flag flag. As a solution , we introduced a timeout ( which is time.ParseDuration valid input), so the test stops if the the tests take more time than the timeout. Currently it is set to 10 seconds.

Closes #1897 

## Checklist

- [x] New and updated code has appropriate documentation
- [ ] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

image

### CODE REVIEW

**Comment by krishnaduttPanchagnula** [comment]
@rootulp can you please resolve the `failed to push ghcr.io/celestiaorg/celestia-app:pr-1900: unexpected status: 403 Forbidden` so we can close this PR?

**Comment by krishnaduttPanchagnula** [comment]
any ideas that you can think of @rootulp for your idea implementation?

**Comment by rootulp** [comment]
Yea so we tend to skip integration tests in `-short` mode with a snippet like:

https://github.com/rootulp/celestia-app/blob/169ad253ce33b94714b655d27c759ab4a9aa7238/app/test/fuzz_abci_test.go#L24-L26

so we ideally want to do that in tests that take > 10 seconds to run

**Comment by rootulp** [comment]
Closing in favor of https://github.com/celestiaorg/celestia-app/pull/1958

**Comment by krishnaduttPanchagnula** [comment]
> want to do that in tests that take > 10 seconds to run

so we have to manually list all the test which are taking long time and use an condition right? @rootulp

**Pull request closed without merging**
