### PR TITLE
docs: organize ADR assets

### LINKED ISSUE #1602: Organize ADR assets
Currently all of the [assets for ADRs](https://github.com/celestiaorg/celestia-app/tree/main/docs/architecture/assets) are in one directory, and its getting cumbersome to find specific files. We should organize them better, which could be as simple as giving each ADR with assets a directory of its own for those assets

`./docs/architecture/assets/adr001/image.jpg`

### PR DESCRIPTION
**Pull request by Chirag018**
Closes #1602

### CODE REVIEW

**Review by rootulp — CHANGES_REQUESTED** [review]
@Chirag018 thanks for working on this! markdownlint will fail until the links in the ADRs are updated to point to the new location. After that, this PR should be good to go.

**Comment by rootulp** [comment]
@Chirag018 this repo attempts to adhere to https://www.conventionalcommits.org/en/v1.0.0/ so it would help if PR titles contained a conventional commit prefix (i.e. "docs: organize ADR assets") because the PR title will show up in auto-generated release notes. Ex. https://github.com/celestiaorg/celestia-app/releases/tag/v0.15.0-rc0

**Comment by Chirag018** [comment]
> @Chirag018 thanks for working on this! markdownlint will fail until the links in the ADRs are updated to point to the new location. After that, this PR should be good to go.

Sorry, my bad, forget to update that!

**Review by rootulp — APPROVED** [review]
LGTM b/c markdownlint passed https://github.com/celestiaorg/celestia-app/actions/runs/4943726033/jobs/8838491962?pr=1736#step:4:152

**Review by cmwaters — APPROVED** [review]
utACK

**Review by evan-forbes — APPROVED** [review]

**Pull request merged**
