### PR TITLE
Go fumpt the qgb-integration branch

### PR DESCRIPTION
**Pull request by SweeXordious**
Applies https://github.com/mvdan/gofumpt on the branch

### CODE REVIEW

**Comment by SweeXordious** [comment]
Depends on https://github.com/celestiaorg/celestia-app/pull/512

**Review by evan-forbes — APPROVED** [review]
approving pending the e2e test passing

**Review by adlerjohn — APPROVED** [review]

**Comment by adlerjohn** [comment]
Can you add a CI job to check this?

**Comment by evan-forbes** [comment]
Yeah I agree with John about using CI. gofumpt is backwards compatible and doesn't do any harm, but whatever linter we choose, we should be consistent instead of one off fixes. 

I'm also in favor of of adding stricter restrictions to golangci, as that's what tendermint and the sdk (and the app currently) use, so that's one less tool contributors have to install.

**Comment by SweeXordious** [comment]
Issue created. Merging.

**Pull request merged**
