### PR TITLE
docs: clarify proofs in ADR 11

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/1724

### CODE REVIEW

**Review by nashqueue — APPROVED** [review]

**Review by evan-forbes — APPROVED** [review]

**Review by MSevey — APPROVED** [review]
Approving for @nashqueue

**Comment by rootulp** [comment]
Screenshot 2023-05-18 at 11 58 38 AM

which requirement isn't met for this to auto-merge? @MSevey is there a rule enabled on this repo that forces PRs to be up-to-date with respect to `main` in order to merge? I would check myself but I don't have permission to see 👀

**Comment by MSevey** [comment]
> respect

@rootulp must be update to date required. I'll remove that.

**Comment by rootulp** [comment]
Thanks! I expect disabling that rule will help a lot

**Pull request merged**
