### PR TITLE
chore!: delete FitsIntoSquare

### PR DESCRIPTION
**Pull request by evan-forbes**
## Overview

we should do this regardless of #2770 (and I could swear we already did), but it was conflicting so I'm making a PR to that branch atm.

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by rootulp — DISMISSED** [review]
Agreed. `FitsInSquare` seems unused outside these locations 

Screenshot 2023-10-25 at 4 30 13 PM

**Comment by cmwaters** [comment]
It seems that `celestia-node` also don't import it. We should predominantly be conscious of them and rollkit before removing methods but this LGTM

**Comment by evan-forbes** [comment]
yeah its a good point we should check with users before removing stuff.

I hope noone is using this! it was introduced forrever ago in the first (or one of the first) versions of the non-interactive defaults

**Comment by rootulp** [comment]
A lot of this code has been extracted to https://github.com/celestiaorg/go-square so I think we should close this as won't do and track in https://github.com/celestiaorg/go-square/issues/4.

**Pull request closed without merging**
