### PR TITLE
chore(deps): upgrade protobuf

### PR DESCRIPTION
**Pull request by rootulp**
Fixes an issue discovered by govulncheck

```
Vulnerability #1: GO-2024-2611
    Infinite loop in JSON unmarshaling in google.golang.org/protobuf
  More info: https://pkg.go.dev/vuln/GO-2024-2611
  Module: google.golang.org/protobuf
    Found in: google.golang.org/protobuf@v1.32.0
    Fixed in: google.golang.org/protobuf@v1.33.0
```

### CODE REVIEW

**Comment by rootulp** [comment]
Blocked on https://github.com/golang/protobuf/issues/1596

**Comment by rootulp** [comment]
govulncheck is still failing because we need to bump to Go 1.22.1 which I'll do in a separate PR.

**Review by staheri14 — APPROVED** [review]
Approving this as it appears the other PR for updating Go is already submitted, so this one can be merged subsequently.

**Review by cmwaters — DISMISSED** [review]
Do we need to bump it in the test ground go mod as well?

**Review by evan-forbes — DISMISSED** [review]

**Comment by rootulp** [comment]
oh strange, after I merged in main and re-ran `make mod` the testground go.mod indirect deps for protobuf were bumped

**Review by staheri14 — APPROVED** [review]

**Review by evan-forbes — APPROVED** [review]

**Pull request merged**
