### PR TITLE
refactor: use `SecondsPerYear`

### PR DESCRIPTION
**Pull request by SurajAnand88**
Closes https://github.com/celestiaorg/celestia-app/issues/2040

### CODE REVIEW

**Comment by rootulp** [comment]
@SurajAnand88 thanks for the contribution! I renamed the PR title to conform to conventional commits. 

Ref: https://github.com/celestiaorg/celestia-app#contributing

**Review by rootulp — DISMISSED** [review]

**Review by evan-forbes — DISMISSED** [review]
can we fix the linter before merging? 

```File is not `gofumpt`-ed```

it appears we just have to call gofumpt -w on a file. If this is problematic @SurajAnand88 for any reason one of us can do this and merge

**Comment by SurajAnand88** [comment]
@evan-forbes I've done the  linting part. Could you please check once is it resolved? Because I'm new to open source.

**Comment by rootulp** [comment]
@SurajAnand88 welcome to open source and we appreciate your contribution! You fixed lint correctly b/c [this check](https://github.com/celestiaorg/celestia-app/actions/runs/5483183501/jobs/9997562141?pr=2043) now succeeds.

**Review by rootulp — APPROVED** [review]

**Comment by SurajAnand88** [comment]
Thanks ❤️

**Review by cmwaters — APPROVED** [review]

**Pull request merged**
