### PR TITLE
chore: backport CI changes to v0.11.x to be able to release

### PR DESCRIPTION
**Pull request by SweeXordious**
## Overview

This is backporting the CI  changes to v0.11.x to be able to release a docker image of v0.11.x to registry.

cc: @sysrex 

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by evan-forbes — APPROVED** [review]
utack obvi but makes sense

**Comment by SweeXordious** [comment]
Can we merge without squash?

**Comment by evan-forbes** [comment]
tried, but there's a branch rule in the way.

**Comment by SweeXordious** [comment]
Asked Sevey, thanks :+1:

**Review by rootulp — APPROVED** [review]

**Pull request merged**
