### PR TITLE
feat!: remove Minter from x/mint genesis state

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/2067

Before this PR, genesis.json looked like:

```json
    "mint": {
      "minter": {
        "inflation_rate": "0.080000000000000000",
        "annual_provisions": "0.000000000000000000",
        "previous_block_time": null,
        "bond_denom": "utia"
      }
    },
```

After this PR, genesis.json should be:

```json
    "mint": {
      "bond_denom": "utia"
    },
```

### CODE REVIEW

**Comment by evan-forbes** [comment]
any update on if this is consensus breaking @rootulp ? if so, we should try to include this in the upgrade consensus breaking release

**Comment by rootulp** [comment]
This is breaking. I attempted to run a celestia-app binary with this change on mocha-3 and encountered:

```
panic: unknown field "minter" in types.GenesisState
```

Is regenerating the genesis.json off the table? If yes, we could remediate by retaining the `minter` field in genesis state and putting bond denom in there and removing everything else. It's not ideal but I expect it to be non-breaking. I'll verify that claim.

BTW script that may be helpful in the future: [mocha-3.sh](https://gist.github.com/rootulp/407f3b02ecd8488176959c96f742801d).

**Comment by rootulp** [comment]
I synced w/ @evan-forbes and we plan on generating a new genesis.json for mocha-4 so this PR is up for consideration.

**Review by cmwaters — APPROVED** [review]
Nice clean up. So basically nothing about minting is parameterised?

**Review by evan-forbes — APPROVED** [review]

**Pull request merged**
