### PR TITLE
chore: issue label and project automation

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/1455

The issue label automation was inspired by https://github.com/celestiaorg/celestia-node/pull/1877
The project automation uses [add-to-project](https://github.com/actions/add-to-project)

### CODE REVIEW

**Comment by rootulp** [comment]
I don't see either of the automation CI checks running on this PR so I don't have confidence that they work as expected. It could be they only run after this merges but I'm suspicious

**Comment by MSevey** [comment]
> I don't see either of the automation CI checks running on this PR so I don't have confidence that they work as expected. It could be they only run after this merges but I'm suspicious

Yea I haven't fully figured out when actions PRs run vs needing to be merged in first. 

Also a second reason why it might not have run is because we are intentionally using the `open` trigger. So PR updates aren't going to trigger it.  iirc the reason for that is for labels we don't want the action to re-add labels we removed for example. Plus there is no reason it needs to run more than once.

**Review by evan-forbes — APPROVED** [review]
utACK and makes sense afaiu 

>I don't see either of the automation CI checks running on this PR so I don't have confidence that they work as expected. It could be they only run after this merges but I'm suspicious

same, unfortunately there's only one way to test this lol and we can adjust with future PRs. we can also try on other repos (not forks, since github treats forks very differently)

**Comment by rootulp** [comment]
I'm going to test in prod 😆

**Pull request merged**
