### PR TITLE
test: skip > 10 sec tests in short mode

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/1897

Before `make test-short` took **~161s**
After `make test-short` took **~20.73**
Times measured via this Makefile command:

```Make
## time-test-short: Measures how long test-short takes
time-test-short:
	@echo "--> Running tests in short mode with timer"
	@time go test -mod=readonly ./... -short -count=1
.PHONY: time-test-short
```

### CODE REVIEW

**Review by evan-forbes — COMMENTED** [review]
unfortuantely we're using the short flag to also stop tests from running using the race detector, so adding blocking these two tests also removes coverage there

if we still want to merge this, perhaps we should create an issue to change the above somehow, such as using a different mechanism to stop tests that don't work with the race detector. Perhaps unrelated, but perhaps we should also review which tests can't run w/ the race detector on since we have hopefully fixed some of the issues with testnode since the last update the sdk

**Comment by rootulp** [comment]
> such as using a different mechanism to stop tests that don't work with the race detector

Agreed. Created https://github.com/celestiaorg/celestia-app/issues/1964

**Comment by cmwaters** [comment]
What's the status of this @rootulp?

**Comment by rootulp** [comment]
> What's the status of this @rootulp?

Blocked on https://github.com/celestiaorg/celestia-app/issues/1964

**Comment by rootulp** [comment]
Worth noting that if we want to continue speeding up `make test-short`, the next place to look would be `github.com/celestiaorg/celestia-app/pkg/square`

```
$ make time-test-short
--> Running tests in short mode with timer
?   	github.com/celestiaorg/celestia-app/app/encoding	[no test files]
?   	github.com/celestiaorg/celestia-app/cmd/celestia-appd	[no test files]
?   	github.com/celestiaorg/celestia-app/cmd/celestia-appd/cmd	[no test files]
?   	github.com/celestiaorg/celestia-app/pkg/appconsts	[no test files]
?   	github.com/celestiaorg/celestia-app/pkg/appconsts/v1	[no test files]
ok  	github.com/celestiaorg/celestia-app/app	0.370s
ok  	github.com/celestiaorg/celestia-app/app/ante	0.699s
ok  	github.com/celestiaorg/celestia-app/app/errors	0.959s
ok  	github.com/celestiaorg/celestia-app/app/test	1.504s
ok  	github.com/celestiaorg/celestia-app/pkg/da	1.604s
ok  	github.com/celestiaorg/celestia-app/pkg/inclusion	1.388s
ok  	github.com/celestiaorg/celestia-app/pkg/namespace	1.253s
?   	github.com/celestiaorg/celestia-app/proto/celestia/da	[no test files]
ok  	github.com/celestiaorg/celestia-app/pkg/proof	0.434s
ok  	github.com/celestiaorg/celestia-app/pkg/shares	0.799s
?   	github.com/celestiaorg/celestia-app/test/util	[no test files]
?   	github.com/celestiaorg/celestia-app/test/util/keeper	[no test files]
?   	github.com/celestiaorg/celestia-app/test/util/network	[no test files]
?   	github.com/celestiaorg/celestia-app/test/util/testfactory	[no test files]
?   	github.com/celestiaorg/celestia-app/tools/blocktime	[no test files]
?   	github.com/celestiaorg/celestia-app/x/blob/client/cli	[no test files]
?   	github.com/celestiaorg/celestia-app/x/mint/client/cli	[no test files]
ok  	github.com/celestiaorg/celestia-app/pkg/square	8.760s
ok  	github.com/celestiaorg/celestia-app/pkg/wrapper	1.177s
ok  	github.com/celestiaorg/celestia-app/test/cmd/txsim	0.717s
ok  	github.com/celestiaorg/celestia-app/test/e2e	0.542s
ok  	github.com/celestiaorg/celestia-app/test/tokenfilter	1.195s
ok  	github.com/celestiaorg/celestia-app/test/txsim	1.288s
ok  	github.com/celestiaorg/celestia-app/test/util/blobfactory	1.668s
ok  	github.com/celestiaorg/celestia-app/test/util/malicious	2.055s
ok  	github.com/celestiaorg/celestia-app/test/util/testnode	0.483s
ok  	github.com/celestiaorg/celestia-app/x/blob	0.986s
ok  	github.com/celestiaorg/celestia-app/x/blob/ante	1.442s
ok  	github.com/celestiaorg/celestia-app/x/blob/client/testutil	0.564s
ok  	github.com/celestiaorg/celestia-app/x/blob/keeper	0.953s
ok  	github.com/celestiaorg/celestia-app/x/blob/types	1.109s
ok  	github.com/celestiaorg/celestia-app/x/blob/types/test	1.184s
ok  	github.com/celestiaorg/celestia-app/x/mint	0.871s
ok  	github.com/celestiaorg/celestia-app/x/mint/client/testutil	0.464s
ok  	github.com/celestiaorg/celestia-app/x/mint/keeper	0.508s
ok  	github.com/celestiaorg/celestia-app/x/mint/simulation	0.704s
?   	github.com/celestiaorg/celestia-app/x/paramfilter	[no test files]
ok  	github.com/celestiaorg/celestia-app/x/mint/test	0.501s
?   	github.com/celestiaorg/celestia-app/x/upgrade	[no test files]
ok  	github.com/celestiaorg/celestia-app/x/mint/types	2.276s
ok  	github.com/celestiaorg/celestia-app/x/paramfilter/test	0.508s
ok  	github.com/celestiaorg/celestia-app/x/qgb	1.696s
ok  	github.com/celestiaorg/celestia-app/x/qgb/client	1.294s
ok  	github.com/celestiaorg/celestia-app/x/qgb/keeper	0.700s
ok  	github.com/celestiaorg/celestia-app/x/qgb/types	0.740s
ok  	github.com/celestiaorg/celestia-app/x/tokenfilter	0.885s
ok  	github.com/celestiaorg/celestia-app/x/upgrade/test	0.580s
```

**Review by evan-forbes — APPROVED** [review]

**Review by SweeXordious — APPROVED** [review]

**Pull request merged**
