### PR TITLE
Micro Celes

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by liamsi — APPROVED** [review]
I do not know if this is the most idiomatic way but I'd simply trust Marko on this!

Thank you so much!

ref: https://github.com/celestiaorg/celestia-app/pull/194#issuecomment-1024892766

**Review by evan-forbes — APPROVED** [review]
awesome! it works as expected. The last thing to change is the default fee denomination, but we can handle that in a different PR imho

As always, thanks @marbar3778 !

**Comment by marbar3778** [comment]
> awesome! it works as expected. The last thing to change is the default fee denomination, but we can handle that in a different PR imho
> 

fees are denominated by the validator, not by the module. Or is this different here?

**Comment by evan-forbes** [comment]
the default fee after initializing is still denominated in `stake`, but we can look into this more later. we might have to use custom cli functions like what was done in #177. I also don't think we should fix this minor change until after we bump to a more recent version of the sdk

**Comment by marbar3778** [comment]
> the default fee after initializing is still denominated in `stake`, but we can look into this more later. we might have to use custom cli functions like what was done in #177. I also don't think we should fix this minor change until after we bump to a more recent version of the sdk

in the app.toml you mean?

**Comment by evan-forbes** [comment]
yeah, that's the only place where I could find any reference to `stake`. I don't think it's worth changing atm, though

**Pull request merged**
