### PR TITLE
chore: add support for QGB in mergify

### PR DESCRIPTION
**Pull request by SweeXordious**
## Overview

- [x] mergify changes
- [ ] `qgb-integration` branch rename to `qgb-v1` (I don't have enough permissions)

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by evan-forbes** [comment]
I like the idea of automating this, but wouldn't essentially open a second PR for every PR?

**Comment by SweeXordious** [comment]
@evan-forbes Any other ideas? I agree, it is too much, but it is the easiest I could think of, aside from cherry picking. I'm fine cherry picking btw

**Comment by evan-forbes** [comment]
I don't have a better solution in mind unfortunately. Is there a way that we could batch mergify? perhaps update the qgb-integration branch once a week or something? We shouldn't be using it for too long hopefully, so I'm also ok with just manually merging on occasion

**Comment by SweeXordious** [comment]
Will close then, and update the branch manually occasionally, every week is good.
For the QGB branch rename, I think it would be better to rename so that anyone knows that it's QGB V1.  What do you think?

**Pull request closed without merging**
