### PR TITLE
V0.12.0 rc2 merge main

### PR DESCRIPTION
**Pull request by evan-forbes**
## Overview

simple PR to merge main into v0.12.x to create the second release candidate.

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

**Comment by evan-forbes** [comment]
personal reminder to merge and not squash

**Review by cmwaters — APPROVED** [review]
👍 

Shouldn't we have the same branch protection rules for these long-lived branches?

**Comment by evan-forbes** [comment]
yeah, we definitely need to protect the release branches. I could swear we used to have a rule for that, but I no longer have permissions to update it or add it back cc @MSevey @liamsi

can we get branch protection for all v*.*.x branches?

**Comment by liamsi** [comment]
`v[0-9].[0-9][0-9].x` is on now

**Pull request merged**
