### PR TITLE
fix: add permissions to docker security build

### PR DESCRIPTION
**Pull request by SweeXordious**
## Overview

fixes https://github.com/celestiaorg/celestia-app/issues/1378

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by jrmanes** [comment]
good one @SweeXordious ! 🙌 

looks like it's working:
https://github.com/celestiaorg/celestia-app/actions/runs/4167493697

**Review by jrmanes — APPROVED** [review]
LGTM 🚀

**Comment by jrmanes** [comment]
@evan-forbes 

if you have some spare time, please approve this one, it fixes the permissions issues.

Already tested in `celestia-node` : [here](https://github.com/celestiaorg/celestia-node/blob/main/.github/workflows/docker-build-common.yml)

Actions executed: [here](https://github.com/celestiaorg/celestia-node/actions/workflows/docker-build-common.yml)

thanks in advance!

**Review by evan-forbes — APPROVED** [review]
this makes sense to me, but I'll defer to @MSevey

**Comment by SweeXordious** [comment]
Matt is on his 2/19 OOO day :D this PR will age quite well :laughing: :laughing:

**Pull request merged**
