### PR TITLE
chore(deps): upgrade to celestiaorg/.github v0.3.1

### PR DESCRIPTION
**Pull request by rootulp**
Supersedes https://github.com/celestiaorg/celestia-app/pull/3024 and https://github.com/celestiaorg/celestia-app/pull/3061

### CODE REVIEW

**Review by MSevey — APPROVED** [review]
👍 
When you update the branch protection rules, only make the github registry run required as the docker and scaleway runs will only work on main if the default on the repo is to use forks. 
This is due to the permission scope issue of secrets on github.

**Review by staheri14 — APPROVED** [review]

**Review by ninabarbakadze — APPROVED** [review]

**Comment by rootulp** [comment]
Maybe this can't merge yet b/c only one code owner approved?

**Review by evan-forbes — APPROVED** [review]

**Comment by rootulp** [comment]
I noticed this may not be able to merge because "docker-security-build / docker-build" is no longer a check and there are 3 new checks (GHCR, Docker, Scaleway). When I went to add a required check for GHCR, I observed multiple (perhaps one per commit?):

Screenshot 2024-02-03 at 11 24 06 AM


@MSevey is this expected? I would've appreciated if the release notes of https://github.com/celestiaorg/.github/releases/tag/v0.3.0 included a step to update branch protection rules.

**Comment by MSevey** [comment]
@rootulp 

> I noticed this may not be able to merge because "docker-security-build / docker-build" is still a required check on this rep but I think it was split into 3 new checks (GHCR, Docker, Scaleway). When I went to add a required check for GHCR, I observed multiple (see screenshot below). @MSevey is this expected? 

Yes the split happened a few releases ago, but it's been buggy which is why app hasn't updated until now. 
The multiple options for each are due to the 3 PRs that have run this action so far I believe. 

You can see in the action tab that this PR generated the `389fe` run.
Screen Shot 2024-02-05 at 9 36 42 AM


> I would've appreciated if the release notes of https://github.com/celestiaorg/.github/releases/tag/v0.3.0 included a step to update branch protection rules.

Yes sorry, we've not been good at release notes on that repo. I'll make sure we are better at that moving forward 🙏

**Comment by rootulp** [comment]
Thanks for the clarification. I just removed the branch protection rule for "docker-security-build / docker-build" so that this PR could merge. 

Then enabled a branch protection rule for "docker-security-build / docker-build (GHCR; ghcr.io/celestiaorg/celestia-app:389fe3b4)"

**Pull request merged**
