### PR TITLE
chore: delete githooks

### PR DESCRIPTION
**Pull request by rootulp**
## Description

Delete githooks b/c they aren't currently helpful. See https://github.com/celestiaorg/celestia-app/issues/674#issuecomment-1234607443

## Motivation

- The pre-commit hook doesn't match the linters enforced by CI
- `precommit` seems unnecessary and should be deleted in favor of `pre-commit`
- https://github.com/celestiaorg/celestia-node/pull/1013#pullrequestreview-1075832524

### CODE REVIEW

**Review by SweeXordious — COMMENTED** [review]
I like this. I am in for enabling the hooks especially the `pre-commit` one and run formatting checks and similar. 
Also, as you said, we will need documentation.
Hope we had something similar to [spotless](https://github.com/diffplug/spotless) in Go.

**Comment by evan-forbes** [comment]
do the precommit's catch anything that the CI doesn't?

**Comment by rootulp** [comment]
> do the precommit's catch anything that the CI doesn't?

The pre-commit hooks don't prevent us from merging PRs that are non-conformant so they don't catch anything that CI misses b/c not all developers who contribute to this repo are enforced to use them. IMO the pre-commit hooks should only be kept and maintained if developers find that they reduce development time (i.e. reduces the time between submitting a PR, noticing your PR failed a lint CI check, and running `make fmt` locally).

If you're curious about the divergence between CI and pre-commit:

## pre-commit
https://github.com/celestiaorg/celestia-app/blob/13076a62c567f624b2508752b7e129467cd71bf9/contrib/githooks/pre-commit#L32-L35

## golangci-lint 
https://github.com/celestiaorg/celestia-app/blob/13076a62c567f624b2508752b7e129467cd71bf9/.golangci.yml#L7-L10

## Notes
- gofmt is handled by the stricter gofumpt
- misspell is handled by both
- goimports is not enforced by our current CI. We can enable it via https://golangci-lint.run/usage/linters/ but it is apparently slow 
    > Most editors have replaced the goimports program with the same functionality provided by a language server like gopls. This mechanism is significantly faster and more powerful, since the language server has more information that is kept up to date, necessary to add missing imports. 

Ref: https://github.com/mvdan/gofumpt#frequently-asked-questions)

**Comment by rootulp** [comment]
> I like this. I am in for enabling the hooks especially the pre-commit one and run formatting checks and similar.

Since this hook is already present in this repo, I assume this means you want to keep it so will close this PR.

**Comment by rootulp** [comment]
Created https://github.com/celestiaorg/celestia-app/issues/674 with the follow-ups.

**Review by SweeXordious — APPROVED** [review]
:rocket:

**Pull request merged**
