### PR TITLE
chore!: merge main to prepare for rc3

### PR DESCRIPTION
**Pull request by evan-forbes**
## Overview

merging main for v1.0.0-rc3

### CODE REVIEW

**Review by rootulp — APPROVED** [review]

**Review by SweeXordious — DISMISSED** [review]

**Comment by SweeXordious** [comment]
@evan-forbes can this PR also be included in this? https://github.com/celestiaorg/celestia-app/pull/1902

**Comment by evan-forbes** [comment]
@SweeXordious yeah thanks for catchiing

that looks like it could be consensus breaking, is it?

**Comment by evan-forbes** [comment]
it appears that the `TestSquareSizeIntegrationTest` is failing for the max hardcoded blocksize quite often in CI but I'm not getting it to fail locally. I'm investigating which change has increased it significantly. The recent update to the sdk might be the culprit, but I'm unsure.

**Comment by SweeXordious** [comment]
> that looks like it could be consensus breaking, is it?

yes, it is consensus breaking, but I believe everything is setup correctly, only the check was missing. So, it shouldn't halt the network

**Review by SweeXordious — APPROVED** [review]

**Pull request merged**
