### PR TITLE
bump core to v1.2.4-tm-v0.35.6

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description

pull all the latest changes from tendermint + our fixes

closes: #XXXX

### CODE REVIEW

**Review by SweeXordious — DISMISSED** [review]
LGTM. The CI apparently needs to be restarted.

**Comment by evan-forbes** [comment]
> LGTM. The CI apparently needs to be restarted.

this is actually a bug that I've been digging into the past few hours. I'm not sure exactly what is going on or if its relevant to tendermint, but it doesn't pop up in the previous v0.35. For some reason, when two validators are used in the big block test, they have trouble coming to consensus with the latest update. There are quite a few rounds, and proposal block parts are gossiped incredibly slowly *sometimes* for large blocks. Its really weird!

This bug pops up on the version that I and a few others are already running on mamaki, and this isn't a problem atm. Really really weird, but I don't think we should merge until this is figured out, so converting to a draft for now.

**Comment by evan-forbes** [comment]
This is blocked by https://github.com/celestiaorg/celestia-core/pull/783

**Comment by evan-forbes** [comment]
> This is blocked by https://github.com/celestiaorg/celestia-core/pull/783

this isn't the case any longer as we instead changed the default peer gossip timeout, which fixed the failing test mentioned earlier

**Review by SweeXordious — APPROVED** [review]

**Review by adlerjohn — APPROVED** [review]

**Review by liamsi — APPROVED** [review]

**Pull request merged**
