### PR TITLE
chore(docs): lists should be surrounded by blank lines in md

### PR DESCRIPTION
**Pull request by SweeXordious**
## Overview

Adding a new line before the list so that the linter doesn't complain.

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by rootulp** [comment]
Is the linter complaining for you locally? I think we may need to bump the version of markdownlint that is running in CI and/or specify a version of markdownlint to install locally so that we don't run into issues like this.

The latest commit on main passes markdown-lint: https://github.com/celestiaorg/celestia-app/actions/runs/5751200172/job/15589466922

**Review by rootulp — APPROVED** [review]

**Comment by SweeXordious** [comment]
> Is the linter complaining for you locally?

Yes, which was weird. But since the change is also idiomatic, the lists should be surrounded by blank lines, I opened a PR

**Review by evan-forbes — APPROVED** [review]
does this not get linted?

**Comment by SweeXordious** [comment]
for some reason it's not failing because of that, I opened an issue to track this: https://github.com/celestiaorg/celestia-app/issues/2212

**Pull request merged**
