### PR TITLE
chore(x/mint)!: shorten keys

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/2497 
Closes https://github.com/celestiaorg/celestia-app/issues/2498

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]

**Comment by rootulp** [comment]
Note this PR is breaking and we haven't come to a decision on whether we include it in v1.0.0 or close it and never do it.

**Comment by cmwaters** [comment]
It's breaking but I don't see much risk in making that change if we already plan on making a breaking change. At the same time, I don't think there's too much to gain

**Review by evan-forbes — COMMENTED** [review]
I don't think we should merge this without either deciding that we want to hardfork the testnets and include this in v1, or add a migration script

**Comment by rootulp** [comment]
+1 we can re-open if we want this for v2.

**Pull request closed without merging**
