### PR TITLE
chore: increase retries and block times in integration test for CI

### PR DESCRIPTION
**Pull request by evan-forbes**
trying some things out to reduce flakiness of CI as its getting extremely annoying

### CODE REVIEW

**Comment by evan-forbes** [comment]
one of the things that is causing issues is that the mempool is full when we submit txs. We don't have access to the full tendermint config needed to increase it until we switch to our own proprietary integration test code 

#829

**Comment by SweeXordious** [comment]
Aah makes sense. Thanks :+1:

**Comment by rahulghangas** [comment]
I'll create the relevant PR to close #829 today

**Comment by evan-forbes** [comment]
closing this, but we might want to incorporate something similar when we are refactoring the testing in https://github.com/celestiaorg/celestia-app/issues/829

**Pull request closed without merging**
