### PR TITLE
fix: single node script (#929)

### PR DESCRIPTION
**Pull request by SweeXordious**
fixes a left pver `--ethereum-address`

(cherry picked from commit eb5fe096368b7c7d48f5df4933cc6b1d9ab70136)

## Overview

Cherry pick eb5fe096368b7c7d48f5df4933cc6b1d9ab70136

Fixes: https://github.com/celestiaorg/celestia-app/issues/2101

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by rootulp — APPROVED** [review]
Thanks @SweeXordious !

**Review by cmwaters — APPROVED** [review]

**Comment by SweeXordious** [comment]
Apparently, we can't merge without Evan

**Comment by rootulp** [comment]
Screenshot 2023-07-14 at 9 55 30 AM

lol yea that's odd, I think this PR will remain blocked on Evan's review potentially b/c it's a protected branch (v0.11.x). Maybe this is a good forcing function to get more ppl added as code owners.

**Comment by cmwaters** [comment]
> Maybe this is a good forcing function to get more ppl added as code owners.

Yeah although it's probably quite unusual that we will need to backport something to a branch like v0.11.x

**Comment by cmwaters** [comment]
cc @evan-forbes when you're available

**Review by evan-forbes — APPROVED** [review]
moar codeowners

**Pull request merged**
