### PR TITLE
add stakedenom by deafult

### PR DESCRIPTION
**Pull request by marbar3778**
## Description

use celes by default

closes https://github.com/celestiaorg/celestia-app/issues/158

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by evan-forbes — APPROVED** [review]
awesome!!! thanks a ton @marbar3778 for doing this!

there's an unused constant, `TokenDenomination`, in the payment keeper package that's been there since this repo has been generated, and I think now would be a great time to remove it

https://github.com/marbar3778/celestia-app/blob/2abfb8b2f6bc3f9a295f398dc218f6010c49977e/x/payment/keeper/keeper.go#L14-L16"

otherwise LGTM :+1: :+1:

**Comment by marbar3778** [comment]
> awesome!!! thanks a ton @marbar3778 for doing this!
> 
> there's an unused constant, `TokenDenomination`, in the payment keeper package that's been there since this repo has been generated, and I think now would be a great time to remove it
> 
> https://github.com/marbar3778/celestia-app/blob/2abfb8b2f6bc3f9a295f398dc218f6010c49977e/x/payment/keeper/keeper.go#L14-L16"
> 
> otherwise LGTM 👍 👍

removed it

**Review by evan-forbes — APPROVED** [review]

**Comment by liamsi** [comment]
I have a question: does this automatically fix the issue that denom and the min denom are both named celes currently (instead of celes and uceles)? (see: https://github.com/celestiaorg/insync/pull/3#discussion_r794977142)

**Comment by marbar3778** [comment]
ah yes, this needs to be uceles instead of celes. I can make the change

**Pull request merged**
