### PR TITLE
chore: upgrade to Go 1.21

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/2321

Separately we can consider dropping the `-compat` flag usage. See https://github.com/celestiaorg/celestia-app/issues/2332 b/c I don't think it's necessary.

### CODE REVIEW

**Comment by evan-forbes** [comment]
do we need to wait for celestia-node to be able to upgrade as well?

**Review by cmwaters — APPROVED** [review]

**Comment by cmwaters** [comment]
`main` on celestia-node is on 1.21 (https://github.com/celestiaorg/celestia-node/blob/440e232999331adf1d1dc034e5ceb8b14e9db5c7/go.mod#L3). Their latest RC is on v1.20

**Comment by rootulp** [comment]
Related: https://github.com/celestiaorg/celestia-app/issues/2321#issuecomment-1690519013

> in my experience, sometimes the go compiler will work fine if a dependency uses a higher version of go, but other times it won't

IDK how to explain that. In my experience, it should be safe for an app to use Go 1.20 and depend on a lib that uses Go 1.21.

**Comment by Wondertan** [comment]
go mod tidy forced us to go1.21. I wanted to keep it 1.20 and just update deps supporting it, but that didn't work

**Review by evan-forbes — APPROVED** [review]

**Pull request merged**
