### PR TITLE
feat: add ability to check if a QGB attestation is in store

### PR DESCRIPTION
**Pull request by SweeXordious**
## Overview

I will need this to check whether attestations are in store or not, without having to query them directly.

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by evan-forbes — APPROVED** [review]
seems reasonable

**Review by rootulp — APPROVED** [review]
[optional] a unit test that verifies the endpoint works as expected

**Comment by cmwaters** [comment]
Is this just for testing or is there another use case for this? Shouldn't the store maintain all attestations within a range

**Comment by SweeXordious** [comment]
> Is this just for testing or is there another use case for this? Shouldn't the store maintain all attestations within a range

It's actually for the orchestrator to check if an attestation is there without querying (as it will be done subsequently). This would be handy to fix a certain orchestrator issue we've had with Arabica. I am still not merging this until I am sure this is what's needed and not something else.

**Comment by evan-forbes** [comment]
> I am still not merging this until I am sure this is what's needed and not something else.

can we convert to a draft and document/discuss the reasoning behind this in an issue? (we should still be able to merge if nothing needs to be changed)

**Comment by SweeXordious** [comment]
good idea, thanks

**Pull request closed without merging**
