### PR TITLE
revert: deduplicate max effective square size

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/3336 by reverting #3294
Opens https://github.com/celestiaorg/celestia-app/issues/2267

## Testing

I observe a consensus failure if I reboot celestia-app on `main`. I don't observe a consensus failure if I reboot celestia-app on this branch after the revert.

### CODE REVIEW

**Comment by evan-forbes** [comment]
do we know what the exact cause is? is the refactor fundementally flawed, or is it just some simple state thingy?

I know its just a nice to have, so perhaps we shelve it for a while, but naively without looking into it, it seems like we could have the refactor w/o the the state issues?

**Comment by cmwaters** [comment]
Yeah I would kind of like to have an idea of why this failed instead of simply blindly reverting it

**Comment by rootulp** [comment]
I was planning on investigating it after getting `main` back to a functional state

**Review by evan-forbes — APPROVED** [review]
> I was planning on investigating it after getting main back to a functional state

makes sense, sgtm!

**Review by staheri14 — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]

**Pull request merged**
