### PR TITLE
chore: update common docker ci pipeline

### PR DESCRIPTION
**Pull request by Bidon15**
## Overview

We have the same building bumps for node https://github.com/celestiaorg/celestia-node/pull/2330
QGB orchestrator already contains the latest version of the common docker build pipeline 

https://github.com/celestiaorg/orchestrator-relayer/blob/main/.github/workflows/docker-build-publish.yml

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by rootulp** [comment]
Related https://github.com/celestiaorg/celestia-app/pull/1852/files

**Comment by evan-forbes** [comment]
@Bidon15 what do you think we should do about the failing the docker-build?

```
#14 DONE 0.0s

#15 exporting to image
#15 exporting layers
#15 exporting layers 3.9s done
#15 exporting manifest sha256:bb3ae26af8031199de3da85d2a6c08a116c2c15dc6218d229d6a8b17b8988632 done
#15 exporting config sha256:8df457b7fb00b7a3c9e7f963d5ecf9c98d0279d9adb95b50e04f7381d172d04b done
#15 exporting attestation manifest sha256:4f59b7df7eb3ff78162ae128d0a246848f1fdf2424aa53b587a03129c2db461d done
#15 exporting manifest list sha256:8ec47048157d1280e682648ab424d0a261adde57992953326659ce8d0bb7b161 done
#15 pushing layers
#15 ...

#16 [auth] celestiaorg/celestia-app:pull,push token for ghcr.io
#16 DONE 0.0s

#15 exporting to image
#15 pushing layers 0.5s done
#15 ERROR: failed to push ghcr.io/celestiaorg/celestia-app:pr-1886: unexpected status: 403 Forbidden
------
 > exporting to image:
------
ERROR: failed to solve: failed to push ghcr.io/celestiaorg/celestia-app:pr-1886: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/celestiaorg/celestia-app:pr-1886: unexpected status: 403 Forbidden
```

**Review by SweeXordious — APPROVED** [review]

**Comment by SweeXordious** [comment]
Could the failing CI be because of write access for @Bidon15 ?
I did the same change in orchestrator-relayer, and it's not failing even if I'm opening PRs from a fork

**Comment by evan-forbes** [comment]
that would make sense, we can merge and revert if necessary

**Comment by SweeXordious** [comment]
@Bidon15 It's failing on my side too: https://github.com/celestiaorg/orchestrator-relayer/actions/runs/5201224908/jobs/9381152550?pr=381

**Pull request merged**
