### PR TITLE
chore: delete empty test file

### PR DESCRIPTION
**Pull request by rootulp**
Thanks @cmwaters for discovering. Appears residual after https://github.com/celestiaorg/celestia-app/pull/1462.

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]

**Review by evan-forbes — APPROVED** [review]

**Comment by rootulp** [comment]
IDK why Github is cancelling workflows

**Review by SweeXordious — APPROVED** [review]

**Comment by rootulp** [comment]
It is not obvious what requirement hasn't been met for this to merge

Screenshot 2023-05-11 at 9 09 58 PM

**Comment by evan-forbes** [comment]
maybe it has to be up to date with main?

**Comment by cmwaters** [comment]
> maybe it has to be up to date with main?

I think so. It might have to do with the tests being required now. If I recall correctly there is a way in the settings that you can toggle on or off whether the PR needs to be up to date with main

**Review by cmwaters — APPROVED** [review]

**Pull request merged**
