### PR TITLE
fix: docker security build

### PR DESCRIPTION
**Pull request by SweeXordious**
Closes https://github.com/celestiaorg/celestia-app/issues/2249

### CODE REVIEW

**Comment by SweeXordious** [comment]
Thanks, I'll continue working on it

**Comment by SweeXordious** [comment]
Closing in favor of  https://github.com/celestiaorg/celestia-app/pull/2272

**Comment by rootulp** [comment]
It looks like this PR accidentally included a bump to go-ethereum which is broken for unrelated reasons. See https://github.com/celestiaorg/celestia-app/pull/2259. I reverted the go-ethereum bump and confirmed this does fix Docker security build.

**Comment by SweeXordious** [comment]
yes 100%, I was this morning debugging ethereum dependency and it's because it uses a version of `exp` package which is not backwards compatible, while upsteam uses an old version.

**Pull request closed without merging**
