### PR TITLE
feat!: override default mempool params

### PR DESCRIPTION
**Pull request by rootulp**
Supersedes https://github.com/celestiaorg/celestia-core/pull/885

Closes https://github.com/celestiaorg/celestia-core/issues/812 
Closes https://github.com/celestiaorg/celestia-core/issues/867
Closes https://github.com/celestiaorg/celestia-app/issues/590

### CODE REVIEW

**Review by evan-forbes — APPROVED** [review]
thanks!! tested locally and it works as expected

**Review by evan-forbes — APPROVED** [review]
thanks!! tested this locally and it worked as expected

**Comment by rootulp** [comment]
One thing I didn't consider until after merging is that it should be possible for validators to override this default param by configuring `~/.celestia-app/config/config.toml`. I'll test shortly.

**Comment by evan-forbes** [comment]
> One thing I didn't consider until after merging is that it should be possible for validators to override this default param by configuring

thanks for testing, I didn't test, but I did check it out the code in the sdk and it looked like we should be good https://github.com/celestiaorg/cosmos-sdk/blob/a78f3e1b2d09a853695c1b85da72a37445d7124f/server/util.go#L201-L225

**Comment by rootulp** [comment]
Tested by adding the following log after [this](https://github.com/rootulp/celestia-core/blob/97c3cce834c0fd0568bebf44c6c2fde6b06626e5/node/node.go#L334-L340):

```go
	logger.Info("config.Mempool.Version", "config.Mempool.Version", config.Mempool.Version)
```

and running
```shell
rm -rf ~/.celestia-app
./scripts/single-node.sh
cat ~/.celestia-app/config.toml // verified that mempool version is "v1"
```

the mempool version configured in `config.toml` is respected so after stopping the node above, overriding the version to `"0"`, and restarting the node, logs indicate that the v0 mempool is in fact being used. E.g.

```
2:48PM INF config.Mempool.Version config.Mempool.Version=v0
```

**Comment by evan-forbes** [comment]
@rootulp was this breaking?

**Comment by rootulp** [comment]
I think so because configuration changes can be considered breaking changes

**Comment by evan-forbes** [comment]
there's no harm in leaving it, but I actually think this is one of the few changes that we can make that is not breaking given that it is strictly a default change (anyone can change this at any time) and its part of the mempool (not consensus critical)

**Comment by rootulp** [comment]
I think it's subject to interpretation but assume we don't mark this change as breaking and a validator upgrades from a celestia-app release before this change to a release after this change. Assume the validator intends to use the FIFO mempool but hasn't overriden any config because the default config previously did what they want. The validator operator  upgrades blindly because the release notes don't mark this as a breaking change so they don't expect any visible behavior change. After the upgrade, the validator (contrary to their desire) is using the prioritized mempool. 

I see your point that it's not consensus critical and is overridable so I think this change could be interpreted as non-breaking but if there's ambiguity on whether a change should be marked breaking vs. non-breaking, I think it's safer to mark as breaking to explicitly call out to consumers behavior changes that they should be aware of when upgrading. In the future (i.e. post mainnet launch), I think we'll have to be much more careful about releasing / labeling breaking changes and make an effort to minimize the number of such changes.

**Comment by evan-forbes** [comment]
> I think we'll have to be much more careful about releasing / labeling breaking changes and make an effort to minimize the number of such changes.

Yes I agree :slightly_smiling_face:. As you and I have discussed in the past, almost everything we do is breaking (except changes to the default config imho :sweat_smile:). 

> upgrades from a celestia-app release before this change to a release after this change

Doesn't this require resetting their config? If they only upgrade binaries (most situations) or use their own custom config (all validator setups and most power users) thier mempool will be the same, that's why I don't see this as breaking.

> I think it's safer to mark as breaking...

okay let's keep it breaking :slightly_smiling_face:.

**Comment by rootulp** [comment]
Oh very good point, the situation I described would involve resetting their config which wouldn't happen if strictly upgrading binaries.

**Pull request merged**
