### PR TITLE
docs(specs): remove root level specification page

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/3751

### CODE REVIEW

**Comment by rootulp** [comment]
Even with this approach, images and links are broken from the root page http://localhost:3000/ but not the specific page http://localhost:3000/specs/data_structures.html

Two potential solutions:
1. Rewrite all links to use absolute paths
2. Introduce an introduction page that acts as the root page

**Comment by rootulp** [comment]
I fixed the links with inspiration from https://cips.celestia.org/ (thanks @jcstein)!

**Comment by jcstein** [comment]
you're welcome. glad to hear it! 

noting that I still have a minor related issue open on [this tasklist](https://github.com/celestiaorg/CIPs/issues/183) for CIPs: 
> - Change page names of README.md's on working groups directory so that they can be linked with page.md instead of index.html, so that it works on github too

Currently, the [WGs overview page](https://cips.celestia.org/wgs/index.html) contains links to each working group. these work on the cips.celestia version https://cips.celestia.org/wgs/index.html, but do not on github https://github.com/celestiaorg/CIPs/blob/main/cips/wgs/README.md

**Review by jcstein — APPROVED** [review]
Screenshot 2024-08-28 at 10 38 23 AM
builds as expected for me. links work on sidebar!

**Review by evan-forbes — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]

**Pull request merged**
