### PR TITLE
chore: merge v0.12.0 rc7 into release branch

### PR DESCRIPTION
**Pull request by evan-forbes**
## Overview

this is just merging v0.12.0 into the v0.12 release branch for posterity, as we might want to create patches

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by SweeXordious — COMMENTED** [review]
LGTM, but I don't understand the difference, `v0.12.x` should be what's on latest main?

**Comment by evan-forbes** [comment]
sorry, it shouldn't have been. I realized after I pushed that git created a new branch instead of checking out the tag

should be fixed now!

**Review by rootulp — COMMENTED** [review]
IIUC this PR is similar to https://github.com/celestiaorg/celestia-app/pull/1277 but this PR is merging `main` into `v0.12.x`. Out of curiosity, are we concerned about the changes between `v0.12.0-rc7` and `main`? I did a cursory scan and I don't see any breaking changes but the reason I ask is because I would expect the `v0.12.x` branch to contain the releases from the `v0.12.x` line (e.g. `v0.12.0`, `v0.12.1`, etc.) and if we intend on using `v0.12.0-rc7` for incentivized testnet, then we may not want current `main` on the `v0.12.x` branch, instead we may want to copy over `v0.12.0-rc7`.

**Comment by rootulp** [comment]
On second thought, what benefit does the `v0.12.x` release branch give us prior to cutting `v0.12.0`? I expect it would be easier to maintain after we cut `v0.12.0` because we will likely cherry-pick fixes to the `v0.12.x` release branch to cut new patch versions but we wouldn't need to do a whole merge from `main`. I defer to your judgement though. If we want to merge `main` to `v0.12.x` and then cut a new RC (i.e. `v0.12.0-rc8`) then I'm onboard if we can get incentivized testnet using that

**Comment by evan-forbes** [comment]
> but this PR is merging main into v0.12.x

@rootulp please see above comment, it should be fixed

**Comment by rootulp** [comment]
🤦 oof sorry not sure how I missed that. Confirmed  67c90ed is the commit for https://github.com/celestiaorg/celestia-app/releases/tag/v0.12.0-rc7 so this LGTM

**Review by rootulp — APPROVED** [review]

**Comment by evan-forbes** [comment]
> On second thought, what benefit does the v0.12.x release branch give us prior to cutting v0.12.0? I expect it would be easier to maintain after we cut v0.12.0 because we will likely cherry-pick fixes to the v0.12.x release branch

exactly, node is stable on v0.12.0-rc7, and we're not pushing any further changes to incentivized testnet, so we need to cut v0.12.0

we will likely have some patch for default changes or minor bug fixes, so having a release branch for that seems beneficial

**Review by SweeXordious — APPROVED** [review]

**Comment by evan-forbes** [comment]
is github broken, it won't merge despite two reviews

**Comment by rootulp** [comment]
We may have a branch protection rule on `v0.12.x` that requires all codeowner approvals

**Comment by evan-forbes** [comment]
lolol okay, I'm the only global codeowner, so since I opened this we can't merge PRs that touch ADR w/o approval

we should fix that in the future by just add all team members as code owners imo. not sure what the goals are with that we should talk with @MSevey, when we get the chance. 

In the mean time, I'll close this so I can approve the same PR opened by @rootulp or @SweeXordious

**Pull request closed without merging**
