### PR TITLE
chore: register blob msg server in module

### PR DESCRIPTION
**Pull request by evan-forbes**
## Overview

This is pretty standard to do in the sdk, not sure how we haven't done this yet given over two years of running the state machine and audits lol 

Everything was still occurring via the legacy sdk.Router, but still... 

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by SweeXordious — APPROVED** [review]
Nice catch. How did it work without having the querier registered?

**Review by rootulp — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]

**Comment by cmwaters** [comment]
> Nice catch. How did it work without having the querier registered?

The querier was registered. The msg server is just for transactions

**Comment by SweeXordious** [comment]
> The msg server is just for transactions

Aaah I see, then how are we sending pay for blob transactions?

**Comment by evan-forbes** [comment]
> Aaah I see, then how are we sending pay for blob transactions?

the sdk was using the legacy mechanism, which we're also registering

https://github.com/celestiaorg/cosmos-sdk/blob/50f4c49034ee97424a43b32e77715f9c8413bb5d/baseapp/baseapp.go#L783-L800

**Pull request merged**
