### PR TITLE
ci: disable link check for doi.org

### PR DESCRIPTION
**Pull request by rootulp**
Attempts to mitigate https://github.com/celestiaorg/celestia-app/issues/1887

### CODE REVIEW

**Comment by rootulp** [comment]
🤷‍♂️ the links it claims are broken all seem to work fine. They're all relative to the data_structures.md page and link to other sections on the page.

**Review by evan-forbes — DISMISSED** [review]
lol maybe we should disable links for that file? that sucks, but it might be better than it throwing a false negative and us ignoring that check constantly

**Comment by cmwaters** [comment]
It doesn't consistently for every subsection within the same file. Here it's able to actually find the link for example

https://github.com/celestiaorg/celestia-app/actions/runs/5316526912/jobs/9626144967?pr=1965#step:4:221

**Comment by rootulp** [comment]
After merging in main, the most recent markdownlint ran successfully. See https://github.com/celestiaorg/celestia-app/actions/runs/5338755234/jobs/9676550256?pr=1965

**Review by evan-forbes — APPROVED** [review]

**Review by cmwaters — APPROVED** [review]

**Pull request merged**
