### PR TITLE
docs: fix URL

### PR DESCRIPTION
**Pull request by goodfirm**
## Overview

The link has expired, replace it with the latest address

### CODE REVIEW

**Review by ninabarbakadze — COMMENTED** [review]
lint failing

**Comment by goodfirm** [comment]
> lint failing

The reason for the failure is that `doc` is not an available type, but `docs` is.

Modified, please review again.

**Review by rootulp — APPROVED** [review]

**Comment by rootulp** [comment]
Note: you may need to run `make proto-gen` and push the changed files to this PR b/c I'm surprised that the docs change didn't manifest in the generated `.pb.go` files yet

**Comment by goodfirm** [comment]
> `make proto-gen`

image

Thank you, I executed this command, but no new files were generated

**Comment by rootulp** [comment]
Oh sorry, on re-read I noticed the only changes were in specs/**/*.proto files so I don't think they will result in any changed generated files. Thanks for the fix!

**Comment by goodfirm** [comment]
> Oh sorry, on re-read I noticed the only changes were in specs/**/*.proto files so I don't think they will result in any changed generated files. Thanks for the fix!

My pleasure.
Thanks for your review!

**Review by rach-id — APPROVED** [review]

**Pull request merged**
