### PR TITLE
Add basic scaffolding for QGB module

### PR DESCRIPTION
**Pull request by SweeXordious**
## Description
Adds basic scaffolding for the QGB module.

closes https://github.com/celestiaorg/celestia-app/issues/197 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by SweeXordious** [comment]
@evan-forbes Please take a look when you have time

**Comment by SweeXordious** [comment]
@evan-forbes if we need to include: https://github.com/celestiaorg/celestia-app/issues/199 also in this PR. Then, I can turn it into draft to add that stuff

**Comment by evan-forbes** [comment]
> @evan-forbes if we need to include: https://github.com/celestiaorg/celestia-app/issues/199 also in this PR. Then, I can turn it into draft to add that stuff

no that was my mistake, we shouldn't attempt to finish that in this PR. This PR introduces the `DataCommitmentConfirm` msg, which confused me briefly. #199 just needs to be clarified.

**Comment by SweeXordious** [comment]
@evan-forbes For the `DataCommitmnetConfirm`, it only contains a dummy field... I can remove it from this PR, then introduce it in the next https://github.com/celestiaorg/celestia-app/issues/199 one. What do you think ?

**Comment by evan-forbes** [comment]
sounds good!

**Comment by SweeXordious** [comment]
@evan-forbes Can you take a look now please. Removed the dummy field from DataCommitment

**Review by evan-forbes — APPROVED** [review]
I think PR is fairly uncontroversial considering that its mostly generated code. Let's change the description so that it doesn't close #197, as we still need another PR to bring over some of the logic of the QGB per https://github.com/celestiaorg/celestia-app/issues/197#issuecomment-1032741073

**Comment by SweeXordious** [comment]
@evan-forbes Should we merge this one, then add the remaining logic in the next PR ?

**Comment by evan-forbes** [comment]
> @evan-forbes Should we merge this one, then add the remaining logic in the next PR ?

yep! I think so

**Pull request merged**
