### PR TITLE
fix: validSequenceLen for padding shares

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/celestiaorg/celestia-app/issues/1816

Tagging @jcstein @tuxcanfly for awareness. I plan on cutting a v0.13.3 release after this merges.

### CODE REVIEW

**Review by evan-forbes — DISMISSED** [review]
do we need to include on main as well?

**Comment by rootulp** [comment]
> do we need to include on main as well?

Yea I want to include the tests in a PR against `main` too: https://github.com/celestiaorg/celestia-app/pull/1817
The implementation change likely isn't necessary b/c the the tests in that PR pass without it.

**Review by cmwaters — APPROVED** [review]
LGTM

Tbh I'm not sure why tail padding doesn't have a normal sequence length (that reflects the amount of bytes it has)

**Comment by rootulp** [comment]
> Tbh I'm not sure why tail padding doesn't have a normal sequence length (that reflects the amount of bytes it has)

For tail padding shares we could have a normal sequence length. The downside is that this would differentiate the schema of tail padding shares from namespace padding shares b/c https://github.com/celestiaorg/celestia-app/issues/783#issuecomment-1419007954

**Comment by rootulp** [comment]
Screenshot 2023-05-24 at 12 39 26 PM

these CI checks won't run b/c the v0.13.x release branch doesn't have https://github.com/celestiaorg/celestia-app/pull/1798 . I think we want them as required checks for `main` and the v1.x release branch but want to revert back to the old required checks for previous release branches @MSevey

**Review by evan-forbes — APPROVED** [review]

**Review by staheri14 — APPROVED** [review]

**Pull request merged**
